title = "PrayinForRain.dev"
baseURL = "https://prayinforrain.github.io/"

# This is what goes in <html lang="">
languageCode = 'ko'

theme = "hugo-blog-awesome"

# This defines how dates are formatted
defaultContentLanguage = "ko"

# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="tags"
    name = 'Tags'
    url = '/tags/'
    weight = 30
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 40

[params]
  sitename = "PrayinforRain.dev"
  defaultColor = "light" # set default color mode: dark or light
  description = "Dev blog of PrayinForRain, a KR frontend engineer"

[params.author]
  avatar = "avatar.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "PrayinforRain"
  name = "Profile picture"
  description = "Frontend Developer"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/prayinforrain"

[[params.socialIcons]]
  name = "email"
  url = "mailto:prayinforrain@naver.com"

[[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

[params.analytics] # for Analytics
  host = "prayinforrain.github.io"
  googleId = "G-63GYNX3VF5"
  naverId = "1940c9395811670"

[params.giscus]         # giscus is a comment system based on GitHub Discussions. see https://giscus.app
  enable = true
  repo = "prayinforrain/prayinforrain.github.io"
  repoId = "R_kgDOItUJmA"
  category = "Announcements"
  categoryId = "DIC_kwDOItUJmM4CTXa0"
  mapping = "pathname"  # comment value is the default value
  strict = 0
  reactionsEnabled = 1
  emitMetadata = 0
  inputPosition = "top"
  theme = "preferred_color_scheme"
  lang = "en"
  loading = "lazy"